# Generated by Django 4.1.13 on 2024-05-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_product_section_product_images_product_section_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_Images",
            new_name="Product_Image",
        ),
    ]
