# Generated by Django 4.1.13 on 2024-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_product_descriptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=500, null=True),
        ),
    ]
