# Generated by Django 4.1.13 on 2024-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelTable(
            name="product",
            table="app_Product",
        ),
    ]
