# Generated by Django 4.1.13 on 2024-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="packing_cost",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tax",
            field=models.IntegerField(null=True),
        ),
    ]
